version: '3.4'

services:
  tp2:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: tp2_image
    network_mode: "host"
    privileged: true
    # cap_add:
    #   - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    environment:
      # - NVIDIA_VISIBLE_DEVICES=all
      # - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY
      - QT_X11_NO_MITSHM = 1
    # runtime: nvidia
    volumes:
      - ./ws_tp2:/ws_tp2
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    # devices:
      # - /dev:/dev
    command: /bin/sh -c "while sleep 1000; do :; done"
    # entrypoint: /ros_entrypoint.sh